### PR TITLE
Release 0.2.0 partial

### PR DESCRIPTION
**Pull request by bluewww**
* Partial PR of #2 which doesn't contain the new RAM models yet

### CODE REVIEW

**Comment by bluewww** [comment]
Branch got protected, can you unprotect please?

**Comment by zarubaf** [comment]
Should be unprotected now. Thanks

**Comment by anga93** [comment]
Hi all,

I tested this IP (branch release-0.2.0-partial) in PULP, on several parallel tests like MatrixMul (float and int), plus other rt-tests (call, fork, dma,..). Everything is working properly. Merging is fine from my side.

**Comment by bluewww** [comment]
Works on PULPissimo too.
Can be merged imo. I suggest tagging it `v0.1.6`.

**Pull request merged**
